pagopa/io-functions-app

WelcomeMessagesActivity/index.ts
This PR fix the below typo error:
=> [#166536717] Typo error in welcome message

README.md, StoreBakendStatus/function.json, StoreBakendStatus/index.ts
Adds a time trigger (scheduled) functions that every 5 minutes saves the status check of the App backend (/info endpoint) to a static JSON into blob storage
=> [#171179889] add backend status check

StoreSpidLogs/__test__/index.test.ts, StoreSpidLogs/function.json, StoreSpidLogs/index.ts
It contains a refactor of SpidMsgItem, in order to include SPID request and response in the same message and store it to a single blob
=> [#172067300] Store single SpID Request/Response blob for logs

azure-pipelines.yml, azure-templates/deploy-steps.yml
The following changes have been implemented in the Azure DevOps pipeline to address zero downtime & fast rollback in production:
- added support for selecting one of the following deployment methods in **production** environment:
- '_deployToStagingSlot_': deploy to 'staging' slot 
- '_deployToProductionSlot_' (**current default**): deploy to 'production' slot (_preconfigured slot_)
- '_deployToStagingSlotAndSwap_': deploy to 'staging' slot and then swap 'staging' with 'production' 
**Note 1**. The default value is now set to _deployToProductionSlot_ to allow developers to continuously deploy in the current infrastructure (without slots). We can change the default to _deployToStagingSlot_ when the 'staging' slot with 'auto swap' on will be available.  
**Note 2**.  The deployment to a …
=> [#172123296] pipeline support to deploy using staging slot

GetVisibleServices/__tests__/handler.test.ts, StartEmailValidationProcess/__tests__/handler.test.ts, StoreSpidLogs/__test__/index.test.ts, StoreSpidLogs/index.ts, __mocks__/mocks.ts, package.json, yarn.lock
- refactor StoreSpidLogs from async method to use context.done instead
- upgraded some packages (needed to integrate application insights initialization)
- fixed some tests to work with newer models
- added application insights initializer
=> [#172308410] refactor StoreSpidLogs and track with Application Insights

SendUserDataProcessingEmailActivity/__tests__/handler.test.ts, SendUserDataProcessingEmailActivity/handler.ts, SendUserDataProcessingEmailActivity/index.ts
Added a custom html to NodeMailer configuration due to error in sending phase.
=> [#172380989] Add html body to DPO's UserDataProcessing email

UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/handler.ts
SendWelcomeMessageActivity must implement azure durable functions retry options in order to manage errors ( and retry welcome messages send in that case ).
=> [#172734823] - Retry on send welcome messages activity

UpsertUserDataProcessing/__tests__/handler.test.ts, UpsertUserDataProcessing/handler.ts, __mocks__/mocks.ts, openapi/index.yaml
- Added check control on upset operation, in order to avoid a new version of a user-data-processing record when an other record already exists with status PENDING or WIP.
- Added Conflict Error on API specs
=> [#172693963] - User Data Processing in progress statuses management

package.json, yarn.lock
Gets rid of the following warning:
```
warning "durable-functions > typedoc@0.17.7" has incorrect peer dependency "typescript@>=3.8.3".
```
=> Upgrades typescript to 3.9.5

UpsertUserDataProcessing/handler.ts
The code didn't considered the `FAILED` status. I reversed the check to look for active statuses (`PENDING` and `WIP`) and return conflict in such cases.
=> [#173921255] Fix conflict case on UserDataProcessing upsert

openapi/index.yaml
While working at [this](https://github.com/pagopa/io-backend/pull/711) we noticed that the `SubscriptionKey` is referencing the wrong header field.
=> [#174877080] Change subscription key header

StoreSpidLogs/__test__/index.test.ts, env.example, jest.config.js
This makes the pipeline tests pass without changes
=> [#175119553] Fix dotenv integration with jest

azure-pipelines.yml, azure-templates/deploy-steps.yml
This PR introduces an healthcheck step just before promoting the staging slot to production. 
* deploy application to Staging slot
* perform an http request against `/info` of the staging slot
* if the request is ok (code == 200)
* switch slot with production
* else
* abort the pipeline
The implementation relies on [this common template](https://github.com/pagopa/azure-pipeline-templates/tree/master/templates/rest-healthcheck). The important concept is the http request is performed by a separate container which needs some configuration, please refer to the template repository for further info.
=> [#175126219] Healthcheck step in pipeline

HandleNHNotificationCallActivity/handler.ts, package.json, utils/__tests__/notification.keepalive.test.ts, utils/__tests__/notification.vanilla.test.ts, utils/notification.ts, yarn.lock
Add agentkeepalive to Notification Hub calls in order to avoid SNAT exhaustion.
=> [#176082784] Add keepalive to notification hub client

EnqueueProfileCreationEventActivity/__tests__/handler.test.ts, EnqueueProfileCreationEventActivity/function.json, EnqueueProfileCreationEventActivity/handler.ts, EnqueueProfileCreationEventActivity/index.ts, UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/handler.ts, UpsertedProfileOrchestrator/index.ts, env.example, package.json, tslint.json, utils/config.ts, yarn.lock
1. New `EnqueueProfileCreationEventActivity`
2. `UpsertedProfileOrchestrator` call `EnqueueProfileCreationEventActivity` when a user profile is activated
3. New config with queue name and FF
When a user profile is activated and ready to receive messages we send a message inside a queue. This operation enables other external operations.
Unit test
io-mock
=> [#IPV-52] Enqueue a message when a User Profile is activated

GetProfile/__tests__/handler.test.ts, GetProfile/handler.ts, GetProfile/index.ts, StoreSpidLogs/__test__/handler.test.ts, StoreSpidLogs/handler.ts, StoreSpidLogs/index.ts, utils/config.ts
- Add `EMAIL_MODE_SWITCH_LIMIT_DATE` in config properties
- `GetProfile` returns isEmailEnabled set to false if profile timestamp is before a specific limit date (see previous bullet), otherwise return the value stored on cosmosdb
- Refactor on `StoreSpidLogs` function for better unit testing
We want that a citizen with an old profile, or even a profile that was upserted before the release limit date, has email notification turned off for default
It has been tested by performing:
- yarn lint
- yarn test
=> [#IP-284] add timestamp check on profile for is_email_enabled

package.json, utils/config.ts, yarn.lock
In order to make Date env variable compliant to App service issue we must to parse Date with Timestamp format
- Move `OPT_OUT_EMAIL_SWITCH_DATE` format to Timestamp
- Upgrade `@pagopa/ts-commons` package
This PR allows us to use Timestamp format on Date env variable
Unit test
=> [#IP-297] Move `OPT_OUT_EMAIL_SWITCH_DATE` to Timestamp format

UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/handler.ts, utils/durable.ts
In order to complete the opt-in/opt-out service model implementation, this PR implements changes on profile's upsert workflow, with particular focus on impacts through Subscription Feed update activities, needed when considering new profile's model involving `servicePreferenceSettingsMode`.
- Update UpsertProfileOrchestrator
- Add unit tests and refactor existing ones
New service model requires changes to Profile Upsert operations in order to be compliant with the new model, by maintaining backward compatibility.
Unit test
=> [#IP-298] Add Subscription feed update logic based on servicePreferenceSetting mode

UpdateSubscriptionsFeedActivity/handler.ts, UpdateSubscriptionsFeedActivity/index.ts, UpsertServicePreferences/__tests__/handler.test.ts, UpsertServicePreferences/handler.ts, UpsertServicePreferences/index.ts, UpsertServicePreferences/subscription_feed.ts, UpsertedProfileOrchestrator/handler.ts, package.json, utils/subscription_feed.ts
In order to complete the opt-in/opt-out service model implemetation, this PR adds subscription feed update while servicePreferences get upserted.
- `UpdateSubscriptionFeedActivity` refactor, in order to be called either from `UpsertedProfileOrchestrator` and `UpsertServicePreferences`
- Update `UpsertServicePreferences`'s handler
- `subscription_feed` utility methods moved apart from handlers functions
Every change made to servicePreference must be registered in subscriptionFeed in order to be consistent while sending notification to users.
Unit test
=> [#IP-299] Add SubscriptionFeed Update on ServicePreference upsert

UpdateProfile/handler.ts, utils/tracking.ts
Trace when a user update their profile with a `LEGACY` preferences mode. The scenario is a user that updates the profile from an old app.
Traces goes under the name `api.profiles.change-service-preferences-mode` with `previousMode` and `nextMode` both `LEGACY`
=> [#IP-307] Add tracking for LEGACY upgrades

SendWelcomeMessagesActivity/handler.ts
atm a new IO user, starting from the welcome message,  can't browser [pagopa web site](https://www.pagopa.it/) 
| welcome message  | pagopa |
| ------------- | ------------- |
=> fix - pagopa web site url

utils/__tests__/storage.test.ts, utils/storage.ts, utils/subscription_feed.ts
* check `response.isSuccessful` only when Error falsy
On some scenarios the Azure table service returns an Error and a `null` response to the callbacks of `insertEntity` and `deleteEntity`. When this happens our code throw an unhandled exception trying to access to `response.isSuccessful`.
Application insights logs show the following error:
```
Exception while executing function: Functions.GetMessage node exited with code 1
'Ingestion endpoint could not be reached. This batch of telemetry items has been lost. Use Disk Retry Caching to enable resending of failed telemetry. Error:',,  Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com,LanguageWorkerConsoleLog[error]
Worker 00e991ee-XXXX-XXXX-XXXX-e2683f821aff uncaught exception (learn more: …
```
=> [#IP-368] table service unhandled exception

StoreSpidLogs/function.json
Azure Storage allows to use a prefix for a faster indexed search, instead of a full scan.
I'm not sure why the current filename layout was picked though.
=> switch fiscalCode with spidRequestId in StoreSpidLogs

CreateProfile/__tests__/handler.test.ts, CreateProfile/handler.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/function.json, UpsertedProfileOrchestrator/handler.ts, UpsertedProfileOrchestrator/index.ts
* Duplicate `UpsertedProfileOrchestratorV2` into `UpsertedProfileOrchestrator` in https://github.com/pagopa/io-functions-app/commit/54c9bda5ea117a91bb580259ca775e94fc45fa1d
* Replace reference to point towards newly created orchestrator in https://github.com/pagopa/io-functions-app/commit/a02c93f5d996323c37cecc760338f3854aa83c2a
We created `UpsertedProfileOrchestratorV2` in #189 to upgrade the orchestrator algorithm without interfering with the running, not-yet-terminated instances. We're now in a stable state and we can restore correct naming. This is the first of two phases:
* deploy bot `UpsertedProfileOrchestratorV2` and `UpsertedProfileOrchestrator`, so that running instances of V2 can terminate while new instances start using the final orchestrator
* remove …
=> [#IP-410] Dismiss `UpsertedProfileOrchestratorV2` step 1: duplication

CreateProfile/__tests__/handler.test.ts, CreateProfile/handler.ts, EmitEventActivity/function.json, EmitEventActivity/index.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, UpsertServicePreferences/__tests__/handler.test.ts, UpsertServicePreferences/function.json, UpsertServicePreferences/handler.ts, UpsertedProfileOrchestratorV2/__tests__/handler.test.ts, UpsertedProfileOrchestratorV2/handler.ts, UpsertedProfileOrchestratorV2/index.ts, utils/config.ts, utils/emitted_events.ts
We need to emit events about how a Citizen updates their subscriptions to services. With this PR, the following events will be emitted:
* `profile:completed`
* `profile:service-preferences-changed`
* `service:subscribed`
At the same time, we no longer publish messages on `EUCOVIDCERT_PROFILE_CREATED_QUEUE_NAME` as the mechanism will be replaced by the webhook mechanism introduced in https://github.com/pagopa/io-functions-public-event-dispatcher
* emit `service:subscribed` on service preference update
* emit `profile:completed` and `profile:service-preferences-changed` on profile update
* remove notification on `EUCOVIDCERT_PROFILE_CREATED_QUEUE_NAME`
Unit tests
=> [#IP-438] Emit domain events about service subscriptions

GetServicePreferences/__tests__/handler.test.ts, GetServicePreferences/handler.ts, GetServicePreferences/index.ts, GetVisibleServices/__tests__/handler.test.ts, UpsertServicePreferences/__tests__/handler.test.ts, UpsertServicePreferences/handler.ts, UpsertServicePreferences/index.ts, __mocks__/mocks.service_preference.ts, openapi/index.yaml, openapi/index.yaml.template, package.json, utils/profiles.ts, utils/service_preferences.ts, utils/services.ts, yarn.lock
Upgrade `io-functions-commons` library
Upgrade `index.yaml.template` type definitions
`GetServicePreferences` for special services replace `is_inbox_enabled` value with the `Activation` status (`true` for `ACTIVE` status, `false` otherwise)
`UpsertServicePreferences` for special services check the `Activation` status, the provided `is_inbox_enabled` must be consistent with the current `Activation` status (`true` for `ACTIVE` status, `false` otherwise)
We need to upgrade the type definitions from `io-functions-commons` to properly handle new SpecialServices.
The API's to interact with service prerences must consider `Activation` for special services.
unit test
=> [#IC-44] Add support for Special Services

openapi/index.yaml, package.json, yarn.lock
The Legal Message could be sent to IO by different PEC-SERVER. IO-APP must return the stored PEC-SERVER sender ID in order to properly manage message nerichment.
add sender service id to  LegalData message model.
Properly retrieve the pec-server id of the legal message sender without relying on external input
unit test
=> [#IC-206] Enable multi-provider for Legal Message

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, .eslintrc.js, .github/workflows/pr-title-linter-and-linker.yaml, Dangerfile.ts, package.json, tsconfig.json, yarn.lock
see commit history
Danger is annoying to mantain due to token management.
We want to globally raplace it with a github action.
=> [#ICC-322]  Replace danger with a github action

NoticeLoginEmailOrchestrator/__tests__/handler.test.ts, NoticeLoginEmailOrchestrator/handler.ts, openapi/index.yaml, openapi/index.yaml.template
* [[#IOPID-1192] added is_email_validated optional field on API call](https://github.com/pagopa/io-functions-app/commit/ccdd5910055c1dbba69cd0accbb5730edb6299ec)
enable fallback login email template to be sent if an user doesn't have a validated email
unit tests
=> [#IOPID-1192] added optional field to endpoint notify-login

AbortUserDataProcessing/handler.ts, GetServicePreferences/handler.ts, MigrateServicePreferenceFromLegacy/handler.ts, OnProfileUpdate/handler.ts, SendTemplatedLoginEmailActivity/handler.ts, SendWelcomeMessagesActivity/handler.ts, StartEmailValidationProcess/__tests__/handler.test.ts, StartEmailValidationProcess/handler.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, UpdateSubscriptionsFeedActivity/handler.ts, UpsertServicePreferences/handler.ts, UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/handler.ts, __mocks__/env-config.mock.ts, __mocks__/mocks.ts, tsconfig.json, utils/__tests__/healthcheck.test.ts, utils/appinsights.ts, utils/config.ts, utils/profiles.ts, utils/service_preferences.ts, utils/storage.ts, utils/tracking.ts
Code refactory after enabling the `strict=true` option in `tsconfig`.
Having a `strict=false` option for Typescript transpiling can generate application and logic errors to handle properly `undefined` or `null` properties. This setting helps to prevent bugs in production.
`build ` and unit test
=> [#IOPID-1449] enable `strict=true` on typescript config

OnProfileUpdate/function.json, extensions.csproj, host.json
* [[#IOPID-2118] updated extension bundle from v3 to v4](https://github.com/pagopa/io-functions-app/commit/06d1394021b0988f4532106fbf1216803a604a9f)
* [aligned extensions.csproj](https://github.com/pagopa/io-functions-app/commit/c56299dcb83c7fb67b7253d03cfabc68b48e9e06)
**NOTE**: `extensions.csproj` file is mostly ignored because we aren't using a .NET language.
The extension bundle specified in `host.json` comes ahead of the `extensions.csproj` file(more info [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=azure-portal%2Cto-premium#manually-install-extensions)), so the `PackageReference` tags are ignored anyway.
**NOTE**: passing from extension bundle v3.x to v4.x doesn't introduce notably changes other than changefeed …
=> [#IOPID-2118] extension bundle update

__mocks__/env-config.mock.ts, env.example, utils/config.ts
Remove `FF_NEW_USERS_EUCOVIDCERT_ENABLED`.
The Feature Flag is no longer needed.
Unit tests.
=> [#IOPID-2334] `FF_NEW_USERS_EUCOVIDCERT_ENABLED` removal
