openapi/index.yaml
=> [#169810481] Revert getservicesbyrecipient

GetService/handler.ts, package.json, yarn.lock
Adds service_metadata fields to ServicePublic
=> [#171312722] adds service_metadata to ServicePublic

azure-pipelines.yml, azure-templates/deploy-steps.yml, azure-templates/make-build-steps.yml, package.json, yarn.lock
I added the Azure DevOps pipelines files to support CI/CD for this repository.
=> [#171549853] Added azure devops pipeline

SendValidationEmailActivity/email_validation.mjml
by now, I've kept the changes to a minimum
=> [#172376654] fix broken image link

SendValidationEmailActivity/index.ts, SendWelcomeMessagesActivity/index.ts, package.json, yarn.lock
This is both for calling the services API and
the MailUP API.
=> [#172435256] Use commons fetch for MailUP API

openapi/index.yaml
updated io-functions-commons version
=> [#172050222] Update API definitions for Receipt Data Model

openapi/index.yaml
- Upgrade io-functions-commons version
- removed `teamdigitale` on openapi definitions ref paths
=> [#172376369] added is test profile flag

package.json, utils/notification.ts, yarn.lock
Fixes a bug calling Notification Hub API (create or update installation). 
Update the typings since we got a useless 'any' that made the bug pop up.
=> [#173182873] fix installation api call

UpsertUserDataProcessing/handler.ts, __mocks__/mocks.ts, openapi/index.yaml, package.json, yarn.lock
- update reference to io-function-commons 10.7.0
- update maybeNewStatus with new status ABORTED
=> [#173783401] Add user data processing status ABORTED

utils/email.ts
Removed hardcoded host `localhost` for development purpose
=> externalize MAILHOG_HOSTNAME

GetService/handler.ts, package.json, yarn.lock
This PR contains:
- An upgrade to io-functions-commons' latest version ( 14.6.0 )
- A minor refactor to `service_metadata` mapping, due to spec changes.
=> [#174770172] Service metadata mapping refactoring

SendWelcomeMessagesActivity/handler.ts
This PR rename every occurrence of the Payment section in Wallet in the welcome message
=> [#175488816] change welcome message

Info/__tests__/handler.test.ts, Info/function.json, Info/handler.ts, Info/index.ts, tsconfig.json, utils/healthcheck.ts
This PR introduce a health checks endpoint for the application:
- GET /api/v1/info
that check for wrong configuration and unreachable resources (cosmosdb, storage, urls)
=> [#175119536] healthcheck endpoint

.gitignore, SendWelcomeMessagesActivity/handler.ts, UpsertedProfileOrchestrator/__tests__/handler.test.ts, UpsertedProfileOrchestrator/handler.ts, UpsertedProfileOrchestrator/index.ts, utils/config.ts
When a User profile is created, is sent a welcome message for the Cashback.
This message is sent only if the `IS_CASHBACK_ENABLED` env var is `true`
=> [#175932626] Send Cashback welcome message

StoreSpidLogs/__test__/index.test.ts, package.json, yarn.lock
=> Add date-fns module

CreateProfile/handler.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, __mocks__/mocks.ts, openapi/index.yaml, package.json, utils/profiles.ts, yarn.lock
- ServicePreferencesSettings version update when mode changes during user update
We want to track a new version of settings if the user changes the mode of his service's preferences.
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build
- yarn lint
- yarn test
=> [#IP-278] ServicePreferencesSettings version update when mode changes

.vscode/launch.json, GetServicePreferences/__tests__/handler.test.ts, GetServicePreferences/function.json, GetServicePreferences/handler.ts, GetServicePreferences/index.ts, __mocks__/mocks.service_preference.ts, openapi/index.yaml, openapi/index.yaml.template, package.json, utils/service_preferences.ts
- Add `GetServicePreference` endpoint
- update `openapi/index.yaml`
- add `openapi/index.yaml.template` and scripts to generate `index.yaml`
Move to Opt-in model for services
Unit tests and io-mock
- [] Chore (nothing changes by a user perspective)
=> [#IP-270] Add GetServicePreference endopoint

GetServicePreferences/__tests__/handler.test.ts, GetServicePreferences/handler.ts, UpsertServicePreferences/__tests__/handler.test.ts, UpsertServicePreferences/function.json, UpsertServicePreferences/handler.ts, UpsertServicePreferences/index.ts, __mocks__/mocks.service_preference.ts, openapi/index.yaml, openapi/index.yaml.template, utils/service_preferences.ts
- Add `UpsertServicePreference` endpoint
- update `openapi/index.yaml.template` 
- update `openapi/index.yaml`
Move to Opt-in model for services
Unit tests and io-mock
- [] Chore (nothing changes by a user perspective)
=> [#IP-269]  Add UpsertServicePreferences endpoint

GetProfile/__tests__/handler.test.ts, GetProfile/handler.ts, GetProfile/index.ts, utils/config.ts
This PR let unmodified isInboxEnabled if Email Opt out feature flag is `false` on `GetProfile` endpoint.
=> Add FF_OPT_OUT_EMAIL_ENABLED Feature flag

SendWelcomeMessagesActivity/handler.ts
- Updated welcome messages
- Removed references to cashback
- Updated info about Services
=> [IRS-67] Update handler.ts

CreateValidationTokenActivity/index.ts, MigrateServicePreferenceFromLegacy/__tests__/handler.test.ts, MigrateServicePreferenceFromLegacy/handler.ts, MigrateServicePreferenceFromLegacy/index.ts, SendValidationEmailActivity/handler.ts, StartEmailValidationProcess/orchestrators.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, UpdateProfile/index.ts, UpdateSubscriptionsFeedActivity/handler.ts, UpsertServicePreferences/handler.ts, UpsertServicePreferences/subscription_feed.ts, __mocks__/tracking.ts, utils/crypto.ts, utils/tracking.ts
* add a module with custom events in https://github.com/pagopa/io-functions-app/commit/f89605fba3884c8e3335c6788da86b50e9b83c97
* trace events on profile update in https://github.com/pagopa/io-functions-app/commit/ed689f4afe5ac7d66c2bfeb9ca61b6ed90884ac2
* trace events on preference migration in https://github.com/pagopa/io-functions-app/commit/cd786fb29f428973a6a5f5d2bfa80749edb72633
* refactor events on subscription feed in https://github.com/pagopa/io-functions-app/pull/185/commits/8816ed7e98b77688c8df8e9884bb75f82127d504
We may need to observe how users handle their service preferences. We are adding two custom events:
* `api.profile.change-service-preferences-mode`
* `api.profile.migrate-legacy-preferences`
=> [#IP-304] Trace custom events for service preferences

CODEOWNERS
* remove file CODEOWNERS
We're changing the approval workflow, enforcement are now defined using limitations on who can write on the `master` branch.
=> [#IP-371] Remove codeonwers

host.json
change durable function storage (change connection string to DURABLE_FUNCTION_STORAGE_CONNECTION_STRING)
close internet access to durable function storage
=> Change durable function storage

package.json, yarn.lock
This a temporary change, to test a new indexed query without bringing to production 21.7.0 version that add other functionalities.
=> [#IP-406] Fixed version of io-functions-commons

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml
- Upgrade azure devops templates to v17
- New healthcheck management
**NOTE**
This PR is in Draft because healthcheck is not yet working properly.
=> Fix healthcheck

openapi/index.yaml, openapi/index.yaml.template, package.json, yarn.lock
Just some small fixes to open api, and clean on examples.
=> Fixes openapi

openapi/index.yaml, openapi/index.yaml.template
Added definition for OrganizationFiscalCode
This missing is breaking api generation.
=> Fixed import in open api spec

CreateProfile/__tests__/handler.test.ts, CreateProfile/handler.ts, UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, UpsertedProfileOrchestratorV2/__tests__/handler.test.ts, UpsertedProfileOrchestratorV2/handler.ts
Following https://github.com/pagopa/io-functions-app/pull/226, we enable the new workflow so that profile-related events are emitted
* use `UpsertedProfileOrchestratorV2`
=> [#IP-438] Emit profile related events

GetVisibleServices/__tests__/handler.test.ts, GetVisibleServices/handler.ts, GetVisibleServices/index.ts, utils/config.ts
The functions config permit to override the blob id and container where the visible services json file is located.
Is needed change dinamically the location of visible services json to optimize the return of National scope services.
unit test
=> [#IC-156] Configurable visible service source with envs

package.json
Update packege.json model generation command with last io-backend swagger
Update packege.json
unit test
=> [#IC-68]  Align backend references to last version

openapi/index.yaml, openapi/index.yaml.template, package.json, yarn.lock
- fix UpsertMessageStatus spec
=> [#IC-391] fix UpsertMessageStatus spec

UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts, openapi/index.yaml, openapi/index.yaml.template, package.json, utils/profiles.ts, yarn.lock
This PR depends on https://github.com/pagopa/io-functions-commons/pull/297
* updated `io-functions-commons` to include the new profile model
* updated `@azure/cosmos` to match the version provided in `io-functions-commons` (to avoid compilation errors)
* added unit tests to check the new optional field while updating a profile
* modified `retrievedProfileToExtendedProfile` to include `pushNotificationsContentType`
* modified `apiProfileToProfile` to include `push_notifications_content_type`
* updated openapi specs
add support for the push notifications content type optional field
unit and integration tests passing
=> [#IOCIT-138] added push notifications content type optional field

.devops/deploy-pipelines.yml, .vscode/settings.json, docker/functions-node-14/Dockerfile, host.json, package.json, yarn.lock
* changed resource groups on the deployment pipeline
* changed `vmImage` from `windows-2019` to `ubuntu-latest` on the deployment pipeline
* added support for the function runtime v4
* updated `@azure/functions` dev dependency
migrating to functions runtime v4
=> [#IOCIT-171] added support for functions v4 runtime

SendWelcomeMessagesActivity/index.ts
=> Fix Fetch with Both HTTP or HTTPS support

StoreSpidLogs/__test__/handler.test.ts, StoreSpidLogs/function.json, StoreSpidLogs/index.ts
⚠️  This PR depends on https://github.com/pagopa/io-backend/pull/1078 and should be deployed once all items containing 'loginType' data have been dequeued ⚠️
See commit history
Include the login type information within the filename alongside other login data.
Unit test, io-mock
=> [#IOPID-1078] Add `loginType` value in spid-logs file name

UpdateProfile/handler.ts, openapi/index.yaml, openapi/index.yaml.template, package.json, yarn.lock
* [[#IOPID-1270] added precondition error type based on fn-commons enum](https://github.com/pagopa/io-functions-app/commit/a49e5af6fbaae28e55fd817fed9c46b25b25a345)
add precondition error type
=> [#IOPID-1270] added precondition error type based on fn-commons enum

GetProfile/__tests__/handler.test.ts, GetProfile/handler.ts, openapi/index.yaml, openapi/index.yaml.template
=> [#IOPID-1264] Raise an error if uniqueness check fails

SendTemplatedLoginEmailActivity/index.ts
* [[#IOPID-1286] changed login email title](https://github.com/pagopa/io-functions-app/commit/ed48ca6de984e418f52556e002952232fe888bb8)
fix title
=> [#IOPID-1286] change login email title

extensions.csproj
The trigger does not start. First tentative is to add CosmosDB PackageReference.
=> fix [#IOPID-1198]: add CosmosDB PackageReference

OnProfileUpdate/function.json
=> [#IOPID-1197] changed collection name

OnProfileUpdate/__tests__/handler.test.ts, OnProfileUpdate/handler.ts
The `ProfileDocument` decoder and function logic
The `ProfileDocument` decoder and function logic was not correct since `email` is not present in every profile. Now, missing email is treated as new not validated email
=> [#IOPID-1197] Added missing email case and fixed profile decode

GetProfile/__tests__/handler.test.ts, GetProfile/handler.ts, __mocks__/mocks.ts
Get profile is failing if email is undefined
=> [#IOPID-1422] fix: Avoid query with undefined email

UpdateProfile/__tests__/handler.test.ts, UpdateProfile/handler.ts
=> [#IOPID-1422] Fix Update Profile when email is undefined

StartEmailValidationProcess/handler.ts
* [[#IOPID-1438] fix: wrong orchestrator name for email validation](https://github.com/pagopa/io-functions-app/commit/e1377e3946a8210087beddc21dc63be6575a46de)
the function handler is using the legacy orchestrator which sends an email with outdated design
integration test via io-mock
=> [#IOPID-1438] fix: wrong orchestrator name for resend of email validation

openapi/index.yaml, openapi/index.yaml.template
=> [#IOPID-1444] fix: updateProfile allOf type

.devops/code-review-pipelines.yml, __integrations__/package.json
=> fix: integration tests not launching in CI

.devops/deploy-pipelines.yml
[[#IOPID-2039] changed deploy pipeline target](https://github.com/pagopa/io-functions-app/commit/95c32b1e3dca478f02cb2b483ac26151960036f4)
new deploy target
=> [#IOPID-2039] changed deploy pipeline target

GetProfile/__tests__/handler.test.ts, GetProfile/handler.ts, GetProfile/index.ts, __mocks__/env-config.mock.ts, utils/config.ts
Remove `FF_OPT_IN_EMAIL_ENABLED` and its usage from `GetProfile`.
The Feature Flag `FF_OPT_IN_EMAIL_ENABLED` is not needed anymore.
Unit tests.
=> [#IOPID-2333] `FF_OPT_IN_EMAIL_ENABLED` removal
